version: '2'
services:
  empmgt-postgresql:
    image: postgres:12.1
    volumes:
      - ~/volumes/employeedb/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=softcode
      - POSTGRES_PASSWORD=
    command: 
      -p 5433
    ports:
      - 127.0.0.1:5433:5433
