version: '3.11'
services:
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.11.5-management
    environment:
      - RABBITMQ_DEFAULT_USER=softcode
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672